package com.ym.lite.automation

object YmCommentDefaults {
    val all: List<String> = listOf(
        "Love this energy 🔥",
        "So good 👏",
        "This made me smile 😊",
        "Great work 🙌",
        "Keep going 🚀",
        "Amazing vibe ✨",
        "Really nice 👌",
        "Well done 💯",
        "This is awesome 🔥",
        "Such a good one 👏",
        "Absolutely loved this ❤️",
        "Great job 🌟",
        "Positive vibes only ✨",
        "This is beautiful 😊",
        "So creative 🎨",
        "Fantastic work 👏",
        "You nailed it 💯",
        "Keep shining 🌟",
        "This is inspiring 🙌",
        "What a great vibe 🔥",
        "Beautifully done ✨",
        "So much positivity 😊",
        "This deserves applause 👏",
        "Wonderful content 💛",
        "Love the creativity 🚀",
        "Super impressive 🔥",
        "Such a happy vibe 😄",
        "Great energy here ⚡",
        "Keep creating 🙌",
        "This is brilliant ✨",
        "Really enjoyed this 😊",
        "Amazing effort 👏",
        "So uplifting 💫",
        "Excellent work 💯",
        "Pure good vibes 🌟",
        "This looks great 👌",
        "Very inspiring ❤️",
        "Love this style ✨",
        "So enjoyable 😄",
        "Keep it up 🚀",
        "Wonderful idea 💡",
        "This is fantastic 🔥",
        "Great creativity 🎉",
        "Made my day 😊",
        "So well done 👏",
        "Love the positivity 💛",
        "Beautiful energy ✨",
        "Amazing as always 🌟",
        "Really impressive 🙌",
        "Keep shining bright ☀️",
        "جميل جدًا 🔥",
        "استمر 👏",
        "محتوى رائع ✨",
        "أحسنت جدًا 🙌",
        "فيديو جميل 😊",
        "إبداع 🔥",
        "رائع جدًا 👌",
        "مميز فعلًا 💯",
        "استمر بهذا الإبداع 🚀",
        "يعطيك العافية 👏",
        "طاقة جميلة جدًا ❤️",
        "عمل رائع 🌟",
        "أجواء إيجابية ✨",
        "شيء جميل فعلًا 😊",
        "إبداع مميز 🎨",
        "شغل ممتاز 👏",
        "أبدعت فعلًا 💯",
        "استمر بالتألق 🌟",
        "محتوى ملهم 🙌",
        "أجواء رائعة 🔥",
        "تنفيذ جميل جدًا ✨",
        "كلها طاقة إيجابية 😊",
        "يستحق التصفيق 👏",
        "محتوى جميل 💛",
        "أحببت الإبداع 🚀",
        "مبهر جدًا 🔥",
        "أجواء مفرحة 😄",
        "طاقة قوية وجميلة ⚡",
        "واصل الإبداع 🙌",
        "فكرة رائعة ✨",
        "استمتعت جدًا 😊",
        "مجهود رائع 👏",
        "محتوى يرفع المعنويات 💫",
        "عمل ممتاز 💯",
        "طاقة إيجابية جميلة 🌟",
        "شكله رائع 👌",
        "ملهم جدًا ❤️",
        "أسلوب جميل ✨",
        "ممتع جدًا 😄",
        "واصل بهذا المستوى 🚀",
        "فكرة جميلة 💡",
        "ممتاز جدًا 🔥",
        "إبداع رائع 🎉",
        "أسعدتني 😊",
        "عمل متقن 👏",
        "أحب هذه الإيجابية 💛",
        "أجواء جميلة ✨",
        "رائع كعادتك 🌟",
        "مميز جدًا 🙌",
        "استمر بالتألق دائمًا ☀️"
    )

    private val legacyV1: List<String> = listOf(
        "Love this energy 🔥",
        "So good 👏",
        "This made me smile 😊",
        "Great work 🙌",
        "Keep going 🚀",
        "Amazing vibe ✨",
        "Really nice 👌",
        "Well done 💯",
        "This is awesome 🔥",
        "Such a good one 👏",
        "جميل جدًا 🔥",
        "استمر 👏",
        "محتوى رائع ✨",
        "أحسنت جدًا 🙌",
        "فيديو جميل 😊",
        "إبداع 🔥",
        "رائع جدًا 👌",
        "مميز فعلًا 💯",
        "استمر بهذا الإبداع 🚀",
        "يعطيك العافية 👏"
    )

    fun isLegacyDefault(comments: List<String>): Boolean = comments == legacyV1
}
