package com.ym.lite

object SupportCommentWheel {
    val english: List<String> = listOf(
        "Keep it up! 👏",
        "Great content! 🙌",
        "Love your work ❤️",
        "You’re doing amazing! 🌟",
        "Keep going, you’ve got this! 💪",
        "Really nice work 👌",
        "Well done! 👏",
        "This deserves more support 🙌",
        "Amazing job! ✨",
        "Keep creating! 🔥",
        "You’re doing great! 👍",
        "Such good content 🌟",
        "Very well made! 👏",
        "Keep up the great work! 💪",
        "This is really good 🙌",
        "Love the effort you put in ❤️",
        "Nice work, keep going! 👏",
        "You deserve more recognition 🌟",
        "Great job as always! 🙌",
        "This is quality content 👌",
        "Keep pushing forward! 💪",
        "Really enjoyed this 👏",
        "You’re on the right track! 🌟",
        "Excellent work 🙌",
        "Keep shining! ✨",
        "Your content keeps getting better 👏",
        "Strong work! 💪",
        "Big support from me 🙌",
        "You’re doing something special 🌟",
        "Keep the momentum going! 🔥",
        "Great energy here! 👏",
        "Love this positive vibe ❤️",
        "You’re improving every time 🌟",
        "Keep doing what you do best 🙌",
        "Fantastic work! 👏",
        "Really impressive 👌",
        "This was worth watching 🙌",
        "Keep sharing great content 🌟",
        "You’ve got real talent 👏",
        "Proud of this progress 💪",
        "Another great one! 🔥",
        "Always a pleasure to watch 🙌",
        "This content deserves attention 🌟",
        "You’re doing an awesome job 👏",
        "Keep moving forward 💪",
        "Much respect for your work 🙌",
        "Great effort as always 👏",
        "You’re building something great 🌟",
        "Keep believing in your work ❤️",
        "This is excellent 👌",
        "Really solid content 👏",
        "You’re making great progress 💪",
        "Keep bringing this energy 🔥",
        "Support all the way 🙌",
        "You’re doing wonderful work 🌟",
        "Nice one! Keep going 👏",
        "This deserves a bigger audience 🙌",
        "Your hard work shows 💪",
        "Keep growing and creating 🌟",
        "Great stuff as usual 👌",
        "Love seeing this progress ❤️",
        "You’re doing better and better 👏",
        "Keep inspiring people 🙌",
        "This is genuinely good 🌟",
        "More of this please! 👏",
        "You’re doing a fantastic job 💪",
        "Keep your head up and keep going 🙌",
        "Excellent content, keep it coming 🌟",
        "Really appreciate your work ❤️",
        "Full support from me 👏"
    )

    val arabic: List<String> = listOf(
        "استمر يا بطل 👏",
        "محتوى جميل جدًا 🌟",
        "تستاهل كل الدعم 🙌",
        "شغل مرتب جدًا 👌",
        "يعطيك العافية ❤️",
        "واصل، أنت مبدع 👏",
        "كل الدعم لك 💪",
        "مستوى رائع، استمر 🌟",
        "محتواك يستحق الانتشار 🙌",
        "أحسنت جدًا 👏",
        "شغل ممتاز 🔥",
        "استمر بنفس القوة 💪",
        "دعم كامل لك 🙌",
        "مبدع كالعادة 🌟",
        "خطوة جميلة للأمام 👏",
        "محتوى يستحق المتابعة ❤️",
        "أداء رائع، واصل 👌",
        "مجهود واضح ويستحق التقدير 👏",
        "استمر، القادم أجمل 🌟",
        "كل التوفيق لك 🙌",
        "شغل احترافي جدًا 👏",
        "محتوى مميز، استمر 🔥",
        "تقدم جميل جدًا 💪",
        "أنت على الطريق الصحيح 🌟",
        "دائمًا للأفضل 🙌",
        "واصل الإبداع 👏",
        "مستوى قوي جدًا 💪",
        "دعم وتشجيع من القلب ❤️",
        "محتوى جميل ومفيد 🌟",
        "بالتوفيق، استمر 🙌"
    )

    val all: List<String> = english + arabic
}
